# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Telnet-Brcd
version:      0.2
version_from: lib/Net/Brcd.pm
installdirs:  site
requires:
    Net::Telnet:                   3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
